export const sales = [
  {
    discount: "-40%",
    image: "/images/gamepad.png",
    name: "HAVIT HV-G92 Gamepad",
    currPrice: "$120",
    prevPrice: "$160",
    rating: 88,
  },
  {
    discount: "-35%",
    image: "/images/keyboard.png",
    name: "AK-900 Wired Keyboard",
    currPrice: "$960",
    prevPrice: "$1160",
    rating: 75,
  },
  {
    discount: "-30%",
    image: "/images/monitor.png",
    name: "IPS LCD Gaming Monitor",
    currPrice: "$370",
    prevPrice: "$400",
    rating: 99,
  },
  {
    discount: "-25%",
    image: "/images/chair.png",
    name: "S-Series Comfort Chair",
    currPrice: "$375",
    prevPrice: "$400",
    rating: 99,
  },
  {
    discount: "-25%",
    image: "/images/gamepad.png",
    name: "HAVIT HV-G92 Gamepad",
    currPrice: "$120",
    prevPrice: "$160",
    rating: 88,
  },
  {
    discount: "-40%",
    image: "/images/monitor.png",
    name: "IPS LCD Gaming Monitor",
    currPrice: "$370",
    prevPrice: "$400",
    rating: 99,
  },
];
